export const SET_DATA_SOURCE = 'SET_DATA_SOURCE';
export const SET_HOURS_DATA_SOURCE = 'SET_HOURS_DATA_SOURCE';
export const SET_CHECKED_ELEMENT = 'SET_CHECKED_ELEMENT';

export const SET_WEATHER = 'SET_WEATHER';

export const SET_DS_VISIBLE_STATE = 'SET_DS_VISIBLE_STATE';
